apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: test
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kyawzawaung321@gmail.com
    privateKeySecretRef:
      name: test
    solvers:
      - http01:
          ingress:
            class: nginx